// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwHkUkkLzkRTzdsTNGBf5GPCn2x8Bn-oA',
    appId: '1:15750480486:web:b23bf11789248be5c1e3a7',
    messagingSenderId: '15750480486',
    projectId: 'whatsappclone-d40e6',
    authDomain: 'whatsappclone-d40e6.firebaseapp.com',
    storageBucket: 'whatsappclone-d40e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmwzlREIPfhbStGys5wkv2UbbmpDf8_Hk',
    appId: '1:15750480486:android:bc5e95bcf9e33834c1e3a7',
    messagingSenderId: '15750480486',
    projectId: 'whatsappclone-d40e6',
    storageBucket: 'whatsappclone-d40e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOJXTSI0Jz1tJD46-wJ_4DCwiysDz7Lec',
    appId: '1:15750480486:ios:2d506ec8f53ff766c1e3a7',
    messagingSenderId: '15750480486',
    projectId: 'whatsappclone-d40e6',
    storageBucket: 'whatsappclone-d40e6.appspot.com',
    iosClientId: '15750480486-0a407gnuf0aqjpon1ri3qallqpk6r276.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
